tator/annotate/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import AnnotateView, welcome, finished, instructions, index


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^annotate/$', AnnotateView.as_view(), name='annotate'),
    url(r'^welcome/$', welcome, name='welcome'),
    url(r'^instructions/$', instructions, name='instructions'),
    url(r'^finished/$', finished, name='finished'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^login/$', auth_views.login, {'template_name': 'annotate/login.html'}, name='login'),
]

tator/tagit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('annotate.urls')),
]

tator/annotate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import post_delete


class Query(models.Model):
    text = models.CharField(max_length=300)
    count = models.IntegerField()
    collection = models.CharField(max_length=50) 
    
    class Meta:
        verbose_name_plural = "queries"

    def __str__(self):
        return "Query: '{}'".format(self.text)

    
class Annotation(models.Model):
    # Values for loc_type (Q2)
    # values are from the 2x2 binary feature space of:
    #   a) is a location explicit in the query
    #   b) is there a place name in the query
    POS_LOC_POS_PLACE = 'YY'
    POS_LOC_NEG_PLACE = 'YN'
    NEG_LOC_POS_PLACE = 'NY'
    NEG_LOC_NEG_PLACE = 'NN'
    
    LOCATION_TYPE_CHOICES = (
        (POS_LOC_POS_PLACE, 'Yes -- with place name'),
        (POS_LOC_NEG_PLACE, 'Yes -- without place name'),
        (NEG_LOC_POS_PLACE, 'No'),
        (NEG_LOC_NEG_PLACE, 'Not applicable'),
    )
    
    # Values for query_type (Q3)
    NAVIGATIONAL = 'NAV'
    INFORMATIONAL_DIRECTED_CLOSED = 'IDC'
    INFORMATIONAL_DIRECTED_OPEN = 'IDO'
    INFORMATIONAL_UNDIRECTED = 'IUN'
    INFORMATIONAL_ADVICE = 'IAD'
    INFORMATIONAL_LOCATE = 'ILO'
    INFORMATIONAL_LIST = 'ILI'
    RESOURCE_DOWNLOAD = 'RDO'
    RESOURCE_ENTERTAINMENT = 'RDE'
    RESOURCE_INTERACT = 'RIN'
    RESOURCE_OBTAIN = 'ROB'
    RESOURCE_MAP = 'RMA'
    
    QUERY_TYPE_CHOICES = (
        #('', 'Please select a query type'),
        (NAVIGATIONAL, 'Web Navigation'),
        (INFORMATIONAL_DIRECTED_CLOSED,
         'Directed - Closed'),
        (INFORMATIONAL_DIRECTED_OPEN,
         'Directed - Open'),
        (INFORMATIONAL_UNDIRECTED,
         'Undirected'),
        (INFORMATIONAL_ADVICE, 'Advice'),
        (INFORMATIONAL_LOCATE, 'Locate'),
        (INFORMATIONAL_LIST, 'List'),
        (RESOURCE_DOWNLOAD, 'Download'),
        (RESOURCE_ENTERTAINMENT, 'Entertainment'),
        (RESOURCE_INTERACT, 'Interact'),
        (RESOURCE_OBTAIN, 'Obtain'),
        (RESOURCE_MAP, 'Map'),
    )

    BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

    is_geo = models.BooleanField(
        verbose_name='1. Is this query best answered with a pin on a map?',
        choices=BOOL_CHOICES,
        default=None,
        help_text='This questions asks whether this query would be most suitably answered by a spatial interface, such as a map or route directions. It could be presented using one or multiple pins, lines and/or regions, or a set of instructions',
    )

    loc_type = models.CharField(
        verbose_name='2. Is a location explicit in the query?',
        max_length=3,
        choices=LOCATION_TYPE_CHOICES,
        default=None,
        help_text='This questions asks whether this query contains a place name or other location reference (e.g., work) relating to Question 1.',
    )

    query_type = models.CharField(
        verbose_name='3. What type of query is this?',
        max_length=3,
        choices=QUERY_TYPE_CHOICES,
        default=None,
        help_text='This questions asks you to classify the query into one of the subcategories of Navigation, Informational and Resource (Rose and Levinson, 2004). Below are the definitions as provided by Rose and Levinson, and examples for each of the categories. ',
    )

    def get_question(self, question_num):
        if question_num == 1:
            return self.is_geo
        elif question_num == 2:
            return self.loc_type
        elif question_num == 3:
            return self.query_type

        print("Not a valid question.")

    @classmethod    
    def get_num_categories(cls, question_num):
        if question_num == 1:
            return 2
        elif question_num == 2:
            return len(cls.LOCATION_TYPE_CHOICES)
        elif question_num == 3:
            return len(cls.QUERY_TYPE_CHOICES)

        print("Not a valid question.")        
        
    def __str__(self):
        return "Annotation: is_geo={}, is_geo_expl={}, query_type={}".format(
            self.is_geo,
            self.loc_type,
            self.query_type,
        )

    
class Skipped(models.Model):
    description = models.TextField()

    
class UserResponse(models.Model):
    query = models.ForeignKey(
        Query,
        on_delete=models.CASCADE,
        related_name="responses",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="responses",
    )
    annotation = models.OneToOneField(
        Annotation,
        null=True,
        on_delete=models.CASCADE,
        related_name='response' 
    )
    skipped = models.OneToOneField(
        Skipped,
        null=True,
        on_delete=models.CASCADE,
        related_name='response' 
    )    
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ("query", "user")

    def __str__(self):
        if self.skipped:
            msg = '{} skipped query "{}" at "{}"'
        else:
            msg = '{} annotated query "{}" at {}'

        return msg.format(self.user, self.query.text, self.timestamp)


@receiver(post_delete, sender=UserResponse)
def post_delete_user_response(sender, instance, *args, **kwargs):
    # Make sure we clean up annotations and skippeds associated with any
    # deleted UserResponse objects 

    if instance.skipped:
        instance.skipped.delete()

    if instance.annotation:
        instance.annotation.delete()


class HtmlMessage(models.Model):

    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100) 
    html = models.TextField()

    def __str__(self):
        return "HTML: {}".format(self.name)

tator/annotate/forms.py
from django.forms import ModelForm, HiddenInput, RadioSelect

from .models import Annotation, Skipped


class AnnotationForm(ModelForm):
    class Meta:
        model = Annotation
        fields = '__all__'
        widgets = {
            'user': HiddenInput(),
            'query': HiddenInput(),
            'is_geo': RadioSelect(),
            'loc_type': RadioSelect(),
            'query_type': RadioSelect(),
        }

    def __init__(self, *args, **kwargs):
        super(AnnotationForm, self).__init__(*args, **kwargs)

        # Django assumes that a booleanfield with no supplied value is
        # false. This makes sense for checkboxes, where not checking it is
        # false, but we've changed to Yes/No radio options, where a response is
        # required
        self.fields['is_geo'].required = True


class SkippedForm(ModelForm):
    class Meta:
        model = Skipped
        fields = '__all__'

tator/annotate/views.py
import random

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.views.generic import View

from .models import UserResponse, Annotation, Query, HtmlMessage
from .forms import AnnotationForm, SkippedForm


@login_required
def index(request):
    return redirect('annotate')


@login_required
def welcome(request):
    welcome = HtmlMessage.objects.get(name='welcome')
    instructions = HtmlMessage.objects.get(name='instructions')
    context = {
        "welcome_html": welcome.html,
        "instructions_html": instructions.html
    }
    return render(request, 'annotate/welcome.html', context)


@login_required
def instructions(request):
    instructions = HtmlMessage.objects.get(name='instructions')
    context = {"instructions_html": instructions.html}
    return render(request, 'annotate/instructions.html', context)


@login_required
def finished(request):
    finished = HtmlMessage.objects.get(name='finished')
    context = {"finished_html": finished.html}
    return render(request, 'annotate/finished.html', context)


@method_decorator(login_required, name='dispatch')
class AnnotateView(View):
    
    def get(self, request):
        # get the first from all queries which the user hasn't either annotated
        # or skipped
        queryset = Query.objects.filter(collection='round1').exclude(responses__user=request.user)
        if not queryset.exists():
            # User is finished annotating
            return redirect('finished')
        else:
            query = random.choice(queryset)
            context = {
                'annotation_form': AnnotationForm(),
                'skipped_form': SkippedForm(),
                'query': query,
            }
            return render(request, 'annotate/annotate.html', context)

    def post(self, request):
        query = Query.objects.get(pk=request.POST['query'])
        skipped_form = SkippedForm(request.POST)
        annotation_form = AnnotationForm(request.POST)

        if skipped_form.is_valid():        
            # User skipped this annotation
            skipped = skipped_form.save()
            response = UserResponse.objects.create(
                user=request.user,
                query=query,
                skipped=skipped
            )
            return redirect('annotate')

        if annotation_form.is_valid():
            # create user's annotation and go to next annotation
            annotation = annotation_form.save()
            response = UserResponse.objects.create(
                user=request.user,
                query=query,
                annotation=annotation
            )
            return redirect('annotate')

        context = {
            'annotation_form': annotation_form,
            'skipped_form': skipped_form,
            'query': query
        }
        return render(request, 'annotate/annotate.html', context)

tator/annotate/templates/annotate/annotate.html
{% extends "annotate/base.html" %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <div id="query-container" >
            <div class="query-label">Query:</div>
            <div class="query-text">{{ query.text }}</div>
        </div>
    </div>
</div>

<div class="row">
<form id="annotation-form" action="{{ request.get_full_path }}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form annotation_form exclude='query_type' form_group_class='form-group col-md-3' %}

    <div class="form-group col-md-3{% if form.errors and not form.query_type.errors %} has-success{% endif %}">
        {% bootstrap_label annotation_form.fields.query_type.label label_class="control-label" label_title=annotation_form.fields.query_type.help_text %}   
        <div id="id_query_type">
            {% for val, choice in annotation_form.fields.query_type.choices %}
            {% if forloop.counter == 1 %}
            <div class="query-category">Web Navigation</div>
            {% endif %}

            {% if forloop.counter == 2 %}
            <div class="query-category">Informational</div>
            {% endif %}
            
            {% if forloop.counter == 8 %}
            <div class="query-category">Resource</div>
            {% endif %}
            
            <div class="radio">
                <label for="id_query_type{{ forloop.counter0 }}">
                    <input id="id_query_type{{ forloop.counter0 }}" {% if annotation_form.query_type.value == val %}checked="checked" {% endif %}name="query_type" type="radio" value="{{ val }}" required>
                    {{ choice }}
                    </input>
                </label>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-md-3">
        {% buttons %}
        <input type="hidden" name="query" value="{{ query.pk }}">
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
        
        {% endbuttons %}
    </div>
</form>

<div class="col-md-3">
<form id="skip-form" action="{{ request.get_full_path }}" method="post" class="form">
    {% csrf_token %}
    <p>If the text is unintelligible as a query, you may skip it. Please provide
    a brief description of the problematic query text, which would make clear
    why it cannot be interpreted as a query.</p>
    {% bootstrap_form skipped_form show_label=False %}
    {% buttons %}
    <input type="hidden" name="query" value="{{ query.pk }}">
    <button id="skip-button" type="submit" name="skip" class="btn btn-primary">
        Skip
    </button>
    {% endbuttons %}
</form>
</div>

</div>
{% endblock %}

tator/annotate/templates/annotate/base.html
{% load staticfiles %}


<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Annotator{% endblock %}</title>
		<link href="{% static 'annotate/bs/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'>
		<link href="{% static 'annotate/annotate.css' %}" rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'annotate/annotate.js' %}"></script>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body>
        <div id="content" class="container-fluid">
	        <div class="row">
                <div class="col-sm-12">
                    {% if request.user.is_authenticated %}
                    <div id="header-links">
                        <a href="/instructions" target="_blank">Instructions</a>
                        |
                        <a href="/logout">Logout</a>
                    </div>
                    {% endif %}
                    <div class="clear-float"></div>
                </div>
            </div>

            {% block content %}{% endblock %}
        </div>
    </body>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="{% static 'annotate/bs/js/bootstrap.min.js' %}"></script>
</html>

tator/annotate/templates/annotate/finished.html
{% extends "annotate/base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="container-fluid">
	<div class="row">
        <div class="col-lg-12">
            {{ finished_html|safe }}
        </div>
    </div>
</div>

{% endblock %}

tator/annotate/templates/annotate/instructions.html
{% extends "annotate/base.html" %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <div id="instructions-container">
            {{ instructions_html|safe }}
        </div>
    </div>
</div>
{% endblock %}

tator/annotate/templates/annotate/login.html
{% extends "annotate/base.html" %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

<form id="login-form" action="{% url 'login' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input type="hidden" name="next" value="/welcome" />
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Login
    </button>
    {% endbuttons %}
</form>
{% endblock %}

tator/annotate/templates/annotate/welcome.html
{% extends "annotate/base.html" %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

<div class="row">
    <div class="col-sm-12">    
        <div id="welcome-container">
            {{ welcome_html|safe }}
        </div>

        <div id="instructions-container">
            {{ instructions_html|safe }}
        </div>

        <form action="/annotate">
            <button class="btn btn-primary">
                Proceed
            </button>
        </form>
    </div>
</div>
{% endblock %}